//"Job Hunt"
//Job Portal [search engine for jobs] DS Project, Dr. Quratulain Rajput
//Maryam Tauqeer 22862, Minal Sarwar 22756, Ramsha Munawar 22738
//This is the GUI class, it contains the MAIN METHOD AS WELL


import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame {

    public GUI() {
        initComponents();
        Insert();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j = new javax.swing.JComboBox<>();
        c = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        s = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Hunt");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setName("f"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 67, 64));
        jLabel1.setText("Jobs Available:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 220, 150, 21);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(72, 67, 64));
        jLabel4.setText("Select Skill:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 100, 140, 21);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(72, 67, 64));
        jLabel5.setText("Select Job Title:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 100, 180, 21);

        j.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        j.setMaximumRowCount(11);
        j.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Manager", "Sales Person", "Communication", "Customer Sales Representative", "Accountant", "Software Developer", "Technical Specialist","Marketer", "Service Executive", "Graphic Designer", "Engineer", "Content Writer", "Teacher", "Artist", "Nurse", "Head of Department", "Assistant", "Supervisor", "Consultant", "Intern", "Officer", "Front Desk Person" }));
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(550, 130, 320, 23);

        c.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        c.setMaximumRowCount(11);
        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Karachi", "Lahore", "Islamabad", "Peshawar", "Sialkot", "Quetta", "Hyderabad", "Bhawalpur", "Multan", "Faisalabad" }));
        c.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(30, 130, 120, 23);

        t.setEditable(false);
        t.setColumns(20);
        t.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        t.setRows(5);
        jScrollPane1.setViewportView(t);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 250, 840, 170);

        s.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        s.setMaximumRowCount(11);
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Web and Ecommerce","Art and Design","Customer Service", "IT", "Marketing", "Engineering", "Finance", "Supply Chain", "Sales", "Admin", "HR and Recruiting", "Healthcare", "Computer Software", "Telecommunication", "Management", "Government", "Retail", "Media", "Warehousing", "Insurance", "Social Service", "Accounting", "Hospitality", "Legal", "Economics", "Consulting", "Publishing", "Construction", "Production", "Education" }));
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s);
        s.setBounds(190, 130, 310, 23);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(72, 67, 64));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 180, 100, 29);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(72, 67, 64));
        jLabel6.setText("Select City:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 100, 110, 21);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 0, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blue and Brown Job Post  Vacancy  Announcement Facebook Post (1).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-30, 0, 930, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (c.getSelectedItem().toString().compareTo("")!=0){
            if (c.getSelectedItem().toString().compareTo("")!=0 && s.getSelectedItem().toString().compareTo("")==0 && j.getSelectedItem().toString().compareTo("")!=0){
                //when city and job title only is selected
                t.setText("");
                JOptionPane.showMessageDialog(this, "Please choose a skill");
            }    
            else if (h.searchCity_Skill_Job(c.getSelectedItem().toString(), s.getSelectedItem().toString(), j.getSelectedItem().toString())!=null){
                String str=h.searchCity_Skill_Job(c.getSelectedItem().toString(), s.getSelectedItem().toString(), j.getSelectedItem().toString()).print();
                t.setText(str);
            }
            else{
                t.setText("");
                JOptionPane.showMessageDialog(this, "No Jobs Found");
            }
        }
        else if (s.getSelectedItem().toString().compareTo("")!=0){
            if (h.searchSkill_Job(s.getSelectedItem().toString(),j.getSelectedItem().toString())!=null){
                String str=h.searchSkill_Job(s.getSelectedItem().toString(),j.getSelectedItem().toString()).print();
                t.setText(str);
            }
            else{
                t.setText("");
                JOptionPane.showMessageDialog(this, "No Jobs Found");
            } 
        }
        
        else if(j.getSelectedItem().toString().compareTo("")!=0){
            if (h.searchJobAlone(j.getSelectedItem().toString())!=null){
                String str=h.searchJobAlone(j.getSelectedItem().toString()).print();
                t.setText(str);
            }
            else{
                t.setText("");
                JOptionPane.showMessageDialog(this, "No Jobs Found");
            }
        }
        else{ //when nothing gets selected
            t.setText("");
            JOptionPane.showMessageDialog(this, "Please make a selection");
        }        

    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public void Insert(){
        try {
            jd= FileReading.fileReading();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Node temp=jd.head; temp!=null; temp=temp.next){
            h.Insert(temp);
        }
        
         
    }
    
    
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    Hashing h= new Hashing(42, 20, 300 , 6300, 60 , 630);
    JobDoubly jd;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c;
    private javax.swing.JComboBox<String> j;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JTextArea t;
    // End of variables declaration//GEN-END:variables
}
